In [1]:
import pandas as pd

In [4]:
df= pd.read_excel("customer_churn.xlsx")
df.head()

,Customer_ID,Gender,Age,Tenure_Months,Contract_Type,Internet_Service,Monthly_Charges,Total_Charges,Payment_Method,Support_Calls,Churn
0,CUST-0001,Female,39,1,Month-to-Month,Fiber Optic,97.34,91.12,Bank Transfer,0,No
1,CUST-0002,Female,40,51,Two Year,Fiber Optic,128.73,6421.67,Electronic Check,4,No
2,CUST-0003,Female,53,5,One Year,No Internet,44.32,206.88,Electronic Check,1,No
3,CUST-0004,Female,60,13,One Year,Fiber Optic,53.95,697.39,Credit Card,3,No
4,CUST-0005,Female,67,19,Month-to-Month,Fiber Optic,121.30,2431.15,Credit Card,2,No

In [5]:
df.shape

(2000, 11)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       2000 non-null   object
 1   Gender            2000 non-null   object
 2   Age               2000 non-null   int64
 3   Tenure_Months     2000 non-null   int64
 4   Contract_Type     2000 non-null   object
 5   Internet_Service  2000 non-null   object
 6   Monthly_Charges   2000 non-null   float64
 7   Total_Charges     2000 non-null   float64
 8   Payment_Method    2000 non-null   object
 9   Support_Calls     2000 non-null   int64
 10  Churn             2000 non-null   object
dtypes: float64(2), int64(3), object(6)
memory usage: 172.0+ KB

In [10]:
## Find the number of churned customers
df["Churn"].value_counts()

Churn
No     1540
Yes     460
Name: count, dtype: int64

In [11]:
## Find the churn percentage
df["Churn"].value_counts(normalize=True)*100

Churn
No     77.0
Yes    23.0
Name: proportion, dtype: float64

In [14]:
## To find the churn rate
churn_rate=(df["Churn"]=="Yes").mean()*100
churn_rate

np.float64(23.0)

In [16]:
## 2. which contract type has more churn
df.groupby("Contract_Type")["Churn"].value_counts()

Contract_Type   Churn
Month-to-Month  No       769
                Yes      320
One Year        No       433
                Yes       75
Two Year        No       338
                Yes       65
Name: count, dtype: int64

In [22]:
## to calculate churn percentage by contract type
df.groupby("Contract_Type")["Churn"].apply( lambda x: (x =="Yes").mean()*100)

## Month-to-Month customers has higher churn rate(29.38%) compared with One year(14.76%) and Two year(16.12%) customers

Contract_Type
Month-to-Month    29.384757
One Year          14.763780
Two Year          16.129032
Name: Churn, dtype: float64

In [19]:
## 3.Does Tenure affect Churn

df["Tenure_Group"]=pd.cut(df["Tenure_Months"],bins=[0,12,24,48,72],labels=["0-12","13-24","25-48","49-72"])
df.head(2)

,Customer_ID,Gender,Age,Tenure_Months,Contract_Type,Internet_Service,Monthly_Charges,Total_Charges,Payment_Method,Support_Calls,Churn,Tenure_Group
0,CUST-0001,Female,39,1,Month-to-Month,Fiber Optic,97.34,91.12,Bank Transfer,0,No,0-12
1,CUST-0002,Female,40,51,Two Year,Fiber Optic,128.73,6421.67,Electronic Check,4,No,49-72

In [21]:
## calculate churn by tenure group
df.groupby("Tenure_Group")["Churn"].apply(lambda x:(x=="Yes").mean()*100)

## Churn decreses when customer Tenure increases.Newer customers(0-12 months) have the highest churn rate at 39.87%, while long-term customers(49=72) have the lowest at 14.51%

C:\Users\TmC\AppData\Local\Temp\ipykernel_11696\3453330037.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Tenure_Group")["Churn"].apply(lambda x:(x=="Yes").mean()*100)

Tenure_Group
0-12     39.873418
13-24    27.966102
25-48    20.987654
49-72    14.516129
Name: Churn, dtype: float64

In [23]:
## 4.Do higher monthly charges relate to high churn?

df["Charge_group"]=pd.cut(df["Monthly_Charges"],bins=[0,50,100,150],labels=["Low","Medium","High"])
df.head(2)

,Customer_ID,Gender,Age,Tenure_Months,Contract_Type,Internet_Service,Monthly_Charges,Total_Charges,Payment_Method,Support_Calls,Churn,Tenure_Group,Charge_group
0,CUST-0001,Female,39,1,Month-to-Month,Fiber Optic,97.34,91.12,Bank Transfer,0,No,0-12,Medium
1,CUST-0002,Female,40,51,Two Year,Fiber Optic,128.73,6421.67,Electronic Check,4,No,49-72,High

In [25]:
## calculate churn rate by charge group
df.groupby("Charge_group")["Churn"].apply(lambda x: (x=="Yes").mean()*100)

## Customers with higher monthly charges show higher churn rate.churn increases from 11.53% in low-charge group to 32.64% in high-charge group

C:\Users\TmC\AppData\Local\Temp\ipykernel_11696\206823224.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Charge_group")["Churn"].apply(lambda x: (x=="Yes").mean()*100)

Charge_group
Low       11.528150
Medium    21.788773
High      32.638889
Name: Churn, dtype: float64

In [26]:
## 5.Do no of support calls relate to churn?

df["Support_call_group"]=pd.cut(df["Support_Calls"],bins=[-1,1,3,5,10],labels=["0-1","2-3","4-5","6+"])
df["Support_call_group"].value_counts().sort_index()

Support_call_group
0-1    695
2-3    950
4-5    299
6+      56
Name: count, dtype: int64

In [28]:
## calculate churn rate by support call group
df.groupby("Support_call_group",observed=True)["Churn"].apply(lambda x:(x=="Yes").mean()*100)

## customers with more support calls have higher churn rate .Churn increases from 18.85% for customers with 0-1 support calls to 33.93% for customers with 6+ calls

Support_call_group
0-1    18.848921
2-3    23.157895
4-5    30.100334
6+     33.928571
Name: Churn, dtype: float64

In [29]:
## 6.Does payment method relate to churn?
df.groupby("Payment_Method")["Churn"].apply(lambda x : (x=="Yes").mean()*100)

## churn varies by payment method .Electronic check has the highest churn rate at 27.83% followed by Bank Transfer at 23.95.Credit card and debit card have lower churn rates at 20.08% and 18.75% respectively.

Payment_Method
Bank Transfer       23.952096
Credit Card         20.078740
Debit Card          18.750000
Electronic Check    27.826087
Name: Churn, dtype: float64

In [30]:
## 7. Does internet service type relate to Churn
df.groupby("Internet_Service")["Churn"].value_counts()

Internet_Service  Churn
DSL               No       575
                  Yes      131
Fiber Optic       No       743
                  Yes      267
No Internet       No       222
                  Yes       62
Name: count, dtype: int64

In [31]:
## calculate churn rate by internet service
df.groupby("Internet_Service")["Churn"].apply(lambda x:(x=="Yes").mean()*100)

## Churn varies by internet serivice type .Fiber optic customers have the highest churn rate at 26.44% compared with 21.83% with no internet and 18.56%  for DSL customers.

Internet_Service
DSL            18.555241
Fiber Optic    26.435644
No Internet    21.830986
Name: Churn, dtype: float64

In [32]:
## 8.Does age relate to churn?

df["Age_group"]=pd.cut(df["Age"],bins=[17,30,45,60,100],labels=["17-30","31-45","46-60","61+"])
df["Age_group"].value_counts().sort_index()

Age_group
17-30    495
31-45    571
46-60    554
61+      380
Name: count, dtype: int64

In [33]:
## calculate churn rate by Age group
df.groupby("Age_group")["Churn"].apply(lambda x:(x=="Yes").mean()*100)

C:\Users\TmC\AppData\Local\Temp\ipykernel_11696\3997416423.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Age_group")["Churn"].apply(lambda x:(x=="Yes").mean()*100)

Age_group
17-30    19.393939
31-45    24.168126
46-60    22.924188
61+      26.052632
Name: Churn, dtype: float64

In [35]:
## 9.Which contract type and internet service combinations has the highest churn 

df.groupby(["Contract_Type","Internet_Service"])["Churn"].value_counts()

Contract_Type   Internet_Service  Churn
Month-to-Month  DSL               No       283
                                  Yes       96
                Fiber Optic       No       375
                                  Yes      180
                No Internet       No       111
                                  Yes       44
One Year        DSL               No       170
                                  Yes       19
                Fiber Optic       No       203
                                  Yes       48
                No Internet       No        60
                                  Yes        8
Two Year        DSL               No       122
                                  Yes       16
                Fiber Optic       No       165
                                  Yes       39
                No Internet       No        51
                                  Yes       10
Name: count, dtype: int64

In [36]:
## calculate churn by combination
df.groupby(["Contract_Type","Internet_Service"])["Churn"].apply(lambda x : (x=="Yes").mean()*100)

## contract type and internet service together  show a clear difference  in churn .Month-to-Month customers have the highest churn across all three internet-Service groups with fiber optic + Month-to-Month  at 32.43%. The lowest rate is DSL +one year at 10.05%.

Contract_Type   Internet_Service
Month-to-Month  DSL                 25.329815
                Fiber Optic         32.432432
                No Internet         28.387097
One Year        DSL                 10.052910
                Fiber Optic         19.123506
                No Internet         11.764706
Two Year        DSL                 11.594203
                Fiber Optic         19.117647
                No Internet         16.393443
Name: Churn, dtype: float64

In [37]:
## 10.Does Gender relate to churn?
df.groupby("Gender")["Churn"].value_counts()

Gender  Churn
Female  No       788
        Yes      235
Male    No       752
        Yes      225
Name: count, dtype: int64

In [38]:
df.groupby("Gender")["Churn"].apply(lambda x:(x=="Yes").mean()*100)

Gender
Female    22.971652
Male      23.029683
Name: Churn, dtype: float64

In [40]:
## 11. How do Churned and retained customers differ?

df.groupby("Churn")[["Age","Tenure_Months","Monthly_Charges","Total_Charges","Support_Calls"]].mean()

## Tenure---Churned customers have lower average tenure(28.88% vs 39.10%)
## Monthly Charges---Churned customers pay more on average (89.79% vs 76.81%)
## Support Calls---Churned customers makes more support calls(2.50% vs 2.13%)
## Age---Churned customers are slightly older on average(45.21% vs 43.48%)
## Total Charges---Churned customers have lower charges(2601.41 vs 3028.97),which is consistent with their lower average tenure.

             Age  Tenure_Months  Monthly_Charges  Total_Charges  Support_Calls
Churn
No     43.483766      39.100649        76.808539    3028.972442       2.138312
Yes    45.210870      28.884783        89.791913    2601.410652       2.502174

In [41]:
## 12. Overall Churn Profile 

categorical_column=["Gender","Contract_Type","Internet_Service","Payment_Method"]

for col in categorical_column:
    print("\n",col)
    print( df.groupby(col)["Churn"].apply( lambda x: (x=="Yes").mean()*100))

 Gender
Gender
Female    22.971652
Male      23.029683
Name: Churn, dtype: float64

 Contract_Type
Contract_Type
Month-to-Month    29.384757
One Year          14.763780
Two Year          16.129032
Name: Churn, dtype: float64

 Internet_Service
Internet_Service
DSL            18.555241
Fiber Optic    26.435644
No Internet    21.830986
Name: Churn, dtype: float64

 Payment_Method
Payment_Method
Bank Transfer       23.952096
Credit Card         20.078740
Debit Card          18.750000
Electronic Check    27.826087
Name: Churn, dtype: float64